### ISSUE TITLE
some data doubled when combining data sets with overlapping values

### ISSUE THREAD

**Issue by js54434** [neutronpy/neutronpy#36]
If I combine two data sets which have partial overlap, it seems that the non-overlapping intensities get doubled, though their times and monitor rates don't change. I don't have this problem if the data sets don't overlap. 

```
import numpy as np
import neutronpy

Data = neutronpy.Data

h = np.asarray([0., 0., 0., 0.])
k = np.asarray([0., 0., 0., 0.])
l = np.asarray([0., 0., 0., 0.])
e = np.asarray([2., 2.5, 3., 4.])
temp = np.asarray([10.,10.,10.,10.])
detector = np.asarray([49., 41., 30., 20.])
monitor = np.asarray([100000., 100000., 100000., 100000.])
time = np.asarray([1., 1., 1., 1.])
data1 = Data(h=h, k=k, l=l, e=e, temp=temp, detector=detector, monitor=monitor, 
        time=time)

h = np.asarray([0., 0., 0.])
k = np.asarray([0., 0., 0.])
l = np.asarray([0., 0., 0.])
e = np.asarray([2.5, 3., 4.])
temp = np.asarray([10., 10., 10.])
detector = np.asarray([44., 33., 22.])
monitor = np.asarray([100000., 100000., 100000.])
time = np.asarray([1., 1., 1.,])
data2 = Data(h=h, k=k, l=l, e=e, temp=temp, detector=detector, monitor=monitor, 
        time=time)
                
data12 = data1 + data2

print(data1.intensity)
print('    ' + str(data2.intensity))
print(data12.intensity)
```

This gets printed:
```
[ 49.  41.  30.  20.]
    [ 44.  33.  22.]
[ 98.  85.  63.  42.]
```

**Comment by pseudocubic** [comment]
This is a result of the (automatic) change in m0 (monitor used to normalize to) when you add the two datasets together. The error is where the additional statistics help though. So when you do this, the error for the non-overlapping points remains the same (in this case, simply doubled to account for the scaling of the intensity), but the error for the overlapping points is less, illustrating the increase in statistics. As far as I can tell this is behaving as expected, since the raw detector counts and monitor rates remain correct.
